// flow-typed signature: 489866e49ef706fd391240ee721cb858
// flow-typed version: <<STUB>>/code-split-component_v1.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'code-split-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'code-split-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'code-split-component/babel' {
  declare module.exports: any;
}

declare module 'code-split-component/lib/babel' {
  declare module.exports: any;
}

declare module 'code-split-component/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'code-split-component/babel.js' {
  declare module.exports: $Exports<'code-split-component/babel'>;
}
declare module 'code-split-component/lib/babel.js' {
  declare module.exports: $Exports<'code-split-component/lib/babel'>;
}
declare module 'code-split-component/lib/index.js' {
  declare module.exports: $Exports<'code-split-component/lib/index'>;
}
