// flow-typed signature: 12f170f20e346aed20ef3163789445d0
// flow-typed version: <<STUB>>/koa-mount_vnext/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-mount'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-mount' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-mount/index' {
  declare module.exports: $Exports<'koa-mount'>;
}
declare module 'koa-mount/index.js' {
  declare module.exports: $Exports<'koa-mount'>;
}
