// flow-typed signature: 4d18c8ea40393d00a79f654243f2b18d
// flow-typed version: <<STUB>>/koa-convert_v^1.2.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-convert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-convert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-convert/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-convert/index' {
  declare module.exports: $Exports<'koa-convert'>;
}
declare module 'koa-convert/index.js' {
  declare module.exports: $Exports<'koa-convert'>;
}
declare module 'koa-convert/test.js' {
  declare module.exports: $Exports<'koa-convert/test'>;
}
