// flow-typed signature: f925ce145392e47a25bd5ed1f2cfc0ab
// flow-typed version: <<STUB>>/spawn-monitor_v^1.1.5/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spawn-monitor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'spawn-monitor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spawn-monitor/dist/createMonitor' {
  declare module.exports: any;
}

declare module 'spawn-monitor/dist/index' {
  declare module.exports: any;
}

declare module 'spawn-monitor/dist/log' {
  declare module.exports: any;
}

declare module 'spawn-monitor/dist/timeDiff' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spawn-monitor/dist/createMonitor.js' {
  declare module.exports: $Exports<'spawn-monitor/dist/createMonitor'>;
}
declare module 'spawn-monitor/dist/index.js' {
  declare module.exports: $Exports<'spawn-monitor/dist/index'>;
}
declare module 'spawn-monitor/dist/log.js' {
  declare module.exports: $Exports<'spawn-monitor/dist/log'>;
}
declare module 'spawn-monitor/dist/timeDiff.js' {
  declare module.exports: $Exports<'spawn-monitor/dist/timeDiff'>;
}
