/**
 * Created by Lucian on 16/09/2016.
 */

// Collections
export const LOAD_COLLECTIONS_REQUEST = 'LOAD_COLLECTIONS_REQUEST';
export const LOAD_COLLECTIONS_SUCCESS = 'LOAD_COLLECTIONS_SUCCESS';
export const LOAD_COLLECTIONS_FAILURE = 'LOAD_COLLECTIONS_FAILURE';

// Single Collection
export const LOAD_COLLECTION_REQUEST = 'LOAD_COLLECTION_REQUEST';
export const LOAD_COLLECTION_SUCCESS = 'LOAD_COLLECTION_SUCCESS';
export const LOAD_COLLECTION_FAILURE = 'LOAD_COLLECTION_FAILURE';
